In [2]:
import numpy as np

In [4]:
celdas = 4
reinas = 3

In [24]:

ini = np.zeros((celdas,celdas), dtype=int)
print(ini)
print()

# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
x = np.eye(celdas, dtype=int)
print(x)
print()
y = np.eye(celdas, k= 0,dtype=int)
print(y)
print()
z = np.flip(y,0)
print(z)
print()

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]



In [ ]:
np.trace(c)
3.0
a = np.arange(8).reshape((2,2,2))
np.trace(a)
array([6, 8])
a = np.arange(24).reshape((2,2,2,3))
np.trace(a).shape
(2, 3)